//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithDataset.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_BOOK
    {
        public int BOOKID { get; set; }
        public int USERID { get; set; }
        public Nullable<System.DateTime> BORROW_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual USER USER { get; set; }
    }
}
